Eps layout
CougsInSpace/CougSat1-Hardware pull request #593
Opened 2020-12-05 23:29 UTC by WattsUp

Fixes #580

2020-12-06 21:56 UTC, hendrikmelse approved these changes
Looks good, can turn orphans off or leave them on for the balancing pours, up to you

2021-02-18 01:28 UTC, jaygon12 commented
-change design contraint or fix match length for I2C.

2021-02-18 01:29 UTC, jaygon12 requested changes
-change design constraint or fix match length for I2C.

2021-03-04 02:00 UTC, jaygon12 approved these changes

2021-03-04 02:07 UTC, merged